### ISSUE TITLE
Browser input type=color eyedropper tool not accessible through window object，Eye Dropper

### ISSUE THREAD

**Issue by dinghaining** [WICG/eyedropper-api#36] opened 2024-06-12 07:10 UTC
My browser, even though it can use the input type=color and clearly has the eyedropper color picker tool inside it, when I try to use the eyedropper directly through the window, it tells me there is no such function.

**Comment by tomayac** [comment] 2024-06-12 07:17
Please see the [compatibility data](https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper/EyeDropper#browser_compatibility) for browser support.

**Comment by dinghaining** [comment] 2024-06-12 07:38
> 请参阅兼容性[数据](https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper/EyeDropper#browser_compatibility)以了解浏览器支持。

I've noticed that Google Chrome version 95 and above support this functionality, but the version I have installed locally is 119.0.6045.124 (the official release version).

**Comment by tomayac** [comment] 2024-06-12 07:48
Then it should be available. Is your site on `https:`?

**Comment by dinghaining** [comment] 2024-06-12 08:11
Unfortunately, I am unable to provide you with an online URL, as this is an internal network project. However, as shown in the image, the rightmost side is the Console opened in the Google Chrome settings page, where the 'Eye Dropper' function is available in the 'window' object. The two images on the left are from other pages, and I can confirm that I have not modified any functions in the prototype chain. Yet, I am still unable to find the 'Eye Dropper' function.
![4a5c53538d8dbb78642e7f00e67b7b7](https://github.com/WICG/eyedropper-api/assets/77276311/85945434-f4e3-4bd9-bfea-c9fcc644bb6a)

**Comment by tomayac** [comment] 2024-06-12 10:58
Whatever the problem is, the API is supported in principle in your browser, so it must be an app issue. Also please note that this is the spec repository and not a support forum. Try StackOverflow instead. Can an admin close the Issue?

**Closed as completed** 2024-06-13 00:43 UTC
